services:
  cms-redis:
    image: redis:7.4.0-bookworm
    container_name: cms-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=local-dev
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  cms-stripe:
    image: stripe/stripe-cli:latest
    container_name: cms-stripe
    env_file:
      - .env
    command: "listen --api-key ${STRIPE_SECRET_KEY} --forward-to ${DOCKER_HOST}:8000/webhook/stripe/"
