# Generated by Django 4.2 on 2024-09-05 04:45

import cms.store_backends
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('photo', models.ImageField(blank=True, null=True, storage=cms.store_backends.PublicMediaStorage, upload_to='profile_pics/', verbose_name='Foto de perfil')),
                ('about', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Acerca de')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'permissions': [('create_content', 'Crear contenidos'), ('edit_content', 'Editar contenidos'), ('publish_content', 'Publicar contenidos'), ('comment_post', 'Comentar contenidos'), ('react_to_post', 'Reaccionar a contenidos'), ('report_post', 'Reportar contenidos'), ('view_content', 'Ver contenidos'), ('edit_is_active', 'Editar estado de contenidos'), ('create_roles', 'Crear roles'), ('edit_roles', 'Editar roles'), ('delete_roles', 'Eliminar roles'), ('assign_roles', 'Asignar roles a usuarios'), ('remove_roles', 'Quitar roles a usuarios'), ('view_roles', 'Ver roles'), ('create_users', 'Crear usuarios'), ('edit_users', 'Editar usuarios'), ('delete_users', 'Eliminar usuarios'), ('block_users', 'Bloquear usuarios'), ('unblock_users', 'Desbloquear usuarios'), ('reset_passwords', 'Restablecer contraseñas'), ('view_users', 'Ver usuarios'), ('create_category', 'Crear categorías'), ('view_category', 'Ver categorías'), ('edit_category', 'Editar categorías'), ('delete_category', 'Eliminar categorías'), ('activate_category', 'Activar categorías'), ('deactivate_category', 'Desactivar categorías')],
            },
        ),
    ]
