# Generated by Django 5.1 on 2024-08-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('create_contentrererere', 'Crear contenidos asdsad asdasdsadasd sa'), ('edit_content', 'Editar contenidos'), ('publish_content', 'Publicar contenidos'), ('create_role', 'crear kahsdakshdkasjdlaskjdlaskjdalsjdlaksdj')]},
        ),
    ]
