# Generated by Django 5.1 on 2024-08-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('create_content', 'Crear contenidos'), ('edit_content', 'Editar contenidos'), ('publish_content', 'Publicar contenidos'), ('manage_roles', 'Gestionar roles')]},
        ),
    ]
