# Generated by Django 4.2 on 2024-10-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_options'),
        ('app', '0003_customuser_stripe_customer_id'),
    ]

    operations = [
    ]
