# Generated by Django 5.1 on 2024-08-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('create_content', 'Crear contenidos'), ('edit_content', 'Editar contenidos'), ('publish_content', 'Publicar contenidos'), ('manage_roles', 'Gestionar roles')]},
        ),
    ]
