# Generated by Django 5.1 on 2024-08-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
