# Generated by Django 5.1 on 2024-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser_about'),
        ('app', '0011_alter_customuser_options'),
    ]

    operations = [
    ]
