# Generated by Django 5.1 on 2024-08-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_create_default_group'),
        ('app', '0012_merge_20240829_0701'),
    ]

    operations = [
    ]
