# Generated by Django 5.1 on 2024-08-29 14:22

import cms.store_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20240829_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=cms.store_backends.PublicMediaStorage, upload_to='profile_pics/'),
        ),
    ]
