# Generated by Django 5.1 on 2024-08-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_customuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
