# Generated by Django 5.1 on 2024-08-30 23:31

import cms.store_backends
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('create_content', 'Crear contenidos'), ('edit_content', 'Editar contenidos'), ('publish_content', 'Publicar contenidos'), ('comment_post', 'Comentar contenidos'), ('react_to_post', 'Reaccionar a contenidos'), ('report_post', 'Reportar contenidos'), ('create_roles', 'Crear roles'), ('edit_roles', 'Editar roles'), ('delete_roles', 'Eliminar roles'), ('assign_roles', 'Asignar roles a usuarios'), ('remove_roles', 'Quitar roles a usuarios'), ('view_roles', 'Ver roles'), ('create_users', 'Crear usuarios'), ('edit_users', 'Editar usuarios'), ('delete_users', 'Eliminar usuarios'), ('block_users', 'Bloquear usuarios'), ('unblock_users', 'Desbloquear usuarios'), ('reset_passwords', 'Restablecer contraseñas'), ('view_users', 'Ver usuarios')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Acerca de'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=cms.store_backends.PublicMediaStorage, upload_to='profile_pics/', verbose_name='Foto de perfil'),
        ),
    ]
