# Generated by Django 4.2 on 2024-09-23 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscription',
            name='state',
            field=models.CharField(choices=[('active', 'Activo'), ('pending_payment', 'Pendiente de pago'), ('cancelled', 'Cancelado')], default='pending_payment', max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='suscription',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='suscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
