# Generated by Django 4.2 on 2024-10-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscription', '0002_suscription_state_alter_suscription_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Suscripción en Stripe'),
        ),
    ]
