# Generated by Django 4.2 on 2024-10-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscription', '0003_suscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscription',
            name='state',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='inactive', max_length=15, verbose_name='Tipo'),
        ),
    ]
