# Generated by Django 4.2 on 2024-10-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscription', '0005_alter_suscription_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscription',
            name='state',
            field=models.CharField(choices=[('active', 'Activo'), ('pending_payment', 'Pendiente de pago'), ('cancelled', 'Cancelado'), ('pending_cancellation', 'Pendiente de cancelación')], default='pending_payment', max_length=20, verbose_name='Tipo'),
        ),
    ]
