# Generated by Django 5.1 on 2024-08-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(max_length=255, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_moderated', models.BooleanField(default=True, verbose_name='Moderado')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Costo')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('type', models.CharField(choices=[('Pago', 'Categoría de Pago'), ('Publico', 'Categoría Pública'), ('Suscriptor', 'Categoría para Suscriptor')], default='Pago', max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
    ]
