# Generated by Django 4.2 on 2024-10-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Precio en Stripe'),
        ),
        migrations.AddField(
            model_name='category',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Producto en Stripe'),
        ),
    ]
