# Generated by Django 4.2 on 2024-10-23 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_stripe_price_id_category_stripe_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(7000)], verbose_name='Costo'),
        ),
    ]
