# Generated by Django 4.2 on 2024-09-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Costo'),
        ),
    ]
