# Generated by Django 4.2 on 2024-09-03 06:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('summary', models.TextField(max_length=255, verbose_name='Resumen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('date_expire', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('date_published', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Archivo adjunto')),
                ('state', models.CharField(choices=[('Borrador', 'Borrador'), ('Revisión', 'Revisión'), ('A publicar', 'A publicar'), ('Publicado', 'Publicado'), ('Inactivo', 'Inactivo')], default='Borrador', max_length=20, verbose_name='Estado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'db_table': 'content',
            },
        ),
    ]
