# Generated by Django 4.2 on 2024-09-05 02:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('summary', models.TextField(max_length=255, verbose_name='Resumen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_create', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('date_expire', models.DateField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('date_published', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('attachment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Archivos adjuntos')),
                ('state', models.CharField(choices=[('Borrador', 'Borrador'), ('Revisión', 'Revisión'), ('A publicar', 'A publicar'), ('Publicado', 'Publicado'), ('Inactivo', 'Inactivo')], default='Borrador', max_length=20, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='category.category', verbose_name='Categoría')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Contenido',
                'verbose_name_plural': 'historical Contenidos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('summary', models.TextField(max_length=255, verbose_name='Resumen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('date_expire', models.DateField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('date_published', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Archivos adjuntos')),
                ('state', models.CharField(choices=[('Borrador', 'Borrador'), ('Revisión', 'Revisión'), ('A publicar', 'A publicar'), ('Publicado', 'Publicado'), ('Inactivo', 'Inactivo')], default='Borrador', max_length=20, verbose_name='Estado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'db_table': 'content',
            },
        ),
    ]
