# Generated by Django 5.1 on 2024-08-31 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='content',
        ),
    ]
