# Generated by Django 4.2 on 2024-09-19 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
