# Generated by Django 4.2 on 2024-09-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='state',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Revisión', 'Revisión'), ('A publicar', 'A publicar'), ('Publicado', 'Publicado'), ('Rechazado', 'Rechazado')], default='Borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
