# Generated by Django 4.2 on 2024-09-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_date_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_expire',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de expiración'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
