# Generated by Django 4.2 on 2024-09-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_dislikes_content_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='rating_avg',
            field=models.FloatField(default=0.0, verbose_name='Promedio de calificacion'),
        ),
        migrations.AddField(
            model_name='historicalcontent',
            name='rating_avg',
            field=models.FloatField(default=0.0, verbose_name='Promedio de calificacion'),
        ),
    ]
