# Generated by Django 4.2 on 2024-09-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_historicalcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Archivos adjuntos'),
        ),
        migrations.AlterField(
            model_name='historicalcontent',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Archivos adjuntos'),
        ),
    ]
