# Generated by Django 4.2 on 2024-09-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_content_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='state',
            field=models.CharField(choices=[('draft', 'Borrador'), ('revision', 'Revisión'), ('to_publish', 'A publicar'), ('publish', 'Publicado'), ('rejected', 'Rechazado'), ('inactive', 'Inactivo')], default='draft', max_length=20, verbose_name='Estado'),
        ),
    ]
