# Generated by Django 4.2 on 2024-10-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_historicalcontent_rating_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='dislikes_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de dislikes'),
        ),
        migrations.AddField(
            model_name='content',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de likes'),
        ),
    ]
