# Generated by Django 4.2 on 2024-10-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_dislikes_count_content_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='content',
            name='rating_avg',
            field=models.FloatField(default=0.0, verbose_name='Promedio de calificación'),
        ),
        migrations.AlterField(
            model_name='historicalcontent',
            name='date_create',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación'),
        ),
    ]
