# Generated by Django 4.2 on 2024-10-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_report_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de visualizaciones'),
        ),
    ]
