# Generated by Django 4.2 on 2024-10-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_content_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='shares_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de compartidos'),
        ),
    ]
