# Generated by Django 4.2 on 2024-10-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_content_shares_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='historicalcontent',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
    ]
