name: CMS Tag & Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'CMS Version'
        required: true
jobs:
  build-and-push-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build & Push Docker Image to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: estebanfern/cms-app
        tags: ${{ github.ref_name }}, latest
        registry: docker.io
        dockerfile: app.Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  build-and-push-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build & Push Docker Image to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: estebanfern/cms-docs
        tags: ${{ github.ref_name }}, latest
        registry: docker.io
        dockerfile: docs.Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}